### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by NathanVosburg** [NathanVosburg/NathanVosburg.github.io#1]
- [ ] add gifs for other projects
- [ ] create gif of background so less intensive
- [ ] add links to stuff?
